version: '3.9' # optional since v1.27.0
services:
  nfl-web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
    environment:
      - REACT_APP_BACKEND_URL=http://0.0.0.0:5000
  nfl-api:
    image: nfl-playoff-challenge-api_web
    ports:
      - 5000:5000
    environment:
      - PORT=5000
