version: "3.9"  # optional since v1.27.0
services:
  nfl-web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
    environment:
      - REACT_APP_BACKEND_URL=http://0.0.0.0:5000
    # environment:
    #   - PORT=${PORT}

  # dev:
  #   user: "${UID}:${GID}"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: development
  #   depends_on:
  #     - "web"
  #   volumes:
  #     - type: bind
  #       source: ./service
  #       target: /opt/service
  #       consistency: cached
  #     - type: bind
  #       source: ./tests
  #       target: /opt/tests
  #       consistency: cached
  #     - ${PWD}/poetry.lock:/opt/pysetup/poetry.lock
  #     - ${PWD}/pyproject.toml:/opt/pysetup/pyproject.toml

